global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'application-metrics'
    static_configs:
      - targets: ['infra-app:8080']
    metrics_path: /actuator/prometheus
