spring:
  application:
    name: infrastructure

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    prometheus:
      access: read_only
springdoc:
  show-actuator: true
