apiVersion: v1
kind: Service
metadata:
  name: infra-app-api
  namespace: infra-app
spec:
  type: NodePort
  selector:
    app: infra-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000