apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ogak343/infrastructure.git
    targetRevision: HEAD
    path: gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true