apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-app
  template:
    metadata:
      labels:
        app: infra-app
    spec:
      containers:
        - name: infra-app
          image: ogabek07/app:latest
          ports:
            - containerPort: 3000