apiVersion: v1
kind: Service
metadata:
  name: generic-rest-api-service
spec:
  type: NodePort
  selector:
    app: generic-rest-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080