apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: generic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generic
  template:
    metadata:
      labels:
        app: generic
    spec:
      containers:
        - name: generic
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: generic
            - name: POSTGRES_USER
              value: generic
            - name: POSTGRES_PASSWORD
              value: generic
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: generic-storage
      volumes:
        - name: generic-storage
          persistentVolumeClaim:
            claimName: generic-pvc
